In [1]:
# imports for array-handling and plotting
import numpy as np
import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt
import seaborn as sns

# let's keep our keras backend tensorflow quiet
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='3'
# for testing on CPU
#os.environ['CUDA_VISIBLE_DEVICES'] = ''

# keras imports for the dataset and building our neural network


In [ ]:
## Use if tf is less than 2.0
from keras.datasets import mnist
from keras.models import Sequential, load_model
from keras.models import load_model
from keras.layers.core import Dense, Dropout, Activation
from keras.utils import np_utils

In [28]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense, RepeatVector, Activation, Dropout
from tensorflow.keras.utils import plot_model
from keras.utils import np_utils

In [49]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()
x_train = X_train[:]

In [30]:
X_train[6]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 145,
        255, 211,  31,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  32, 237,
        253, 252,  71,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [31]:
X_train.shape

(60000, 28, 28)

In [32]:
y_train.shape

(60000,)

In [52]:
X_test.shape

(10000, 28, 28)

In [33]:
y_test.shape

(10000,)

In [34]:
y_test[7777]

5

In [35]:
sns.countplot(y_train)

In [36]:
print("X_train shape", X_train.shape)
print("y_train shape", y_train.shape)
print("X_test shape", X_test.shape)
print("y_test shape", y_test.shape)
X_train = X_train.reshape(60000, 784)
X_test = X_test.reshape(10000, 784)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
print("Train matrix shape", X_train.shape)
print("Test matrix shape", X_test.shape)

X_train shape (60000, 28, 28)
y_train shape (60000,)
X_test shape (10000, 28, 28)
y_test shape (10000,)
Train matrix shape (60000, 784)
Test matrix shape (10000, 784)


In [37]:
np.unique(y_train, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8),
 array([5923, 6742, 5958, 6131, 5842, 5421, 5918, 6265, 5851, 5949],
       dtype=int64))

In [38]:
# one-hot encoding using keras' numpy-related utilities
n_classes = 10
print("Shape before one-hot encoding: ", y_train.shape)
Y_train = np_utils.to_categorical(y_train, n_classes)
Y_test = np_utils.to_categorical(y_test, n_classes)
print("Shape after one-hot encoding: ", Y_train.shape)

Shape before one-hot encoding:  (60000,)
Shape after one-hot encoding:  (60000, 10)


In [39]:
Y_test[7777]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [40]:
# building a linear stack of layers with the sequential model
model = tf.keras.Sequential()

model.add(Dense(512, input_shape=(784,)))
model.add(Activation('relu'))                            
model.add(Dropout(0.2))

model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.2))

model.add(Dense(10))
model.add(Activation('softmax'))

In [41]:
# compiling the sequential model
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

In [42]:
# training the model and saving metrics in history
history = model.fit(X_train, Y_train,
#mid batch mode batch size (stochastic mode equal to one and batch mode is equal to total dataset and equavalent to epoch)
          batch_size=128, epochs=20,
          verbose=2,
          validation_data=(X_test, Y_test))



Train on 60000 samples, validate on 10000 samples
Epoch 1/20
60000/60000 - 6s - loss: 0.2510 - accuracy: 0.9247 - val_loss: 0.1034 - val_accuracy: 0.9681
Epoch 2/20
60000/60000 - 5s - loss: 0.0994 - accuracy: 0.9693 - val_loss: 0.0769 - val_accuracy: 0.9745
Epoch 3/20
60000/60000 - 5s - loss: 0.0718 - accuracy: 0.9771 - val_loss: 0.0682 - val_accuracy: 0.9790
Epoch 4/20
60000/60000 - 5s - loss: 0.0538 - accuracy: 0.9833 - val_loss: 0.0709 - val_accuracy: 0.9769
Epoch 5/20
60000/60000 - 5s - loss: 0.0458 - accuracy: 0.9852 - val_loss: 0.0696 - val_accuracy: 0.9808
Epoch 6/20
60000/60000 - 6s - loss: 0.0391 - accuracy: 0.9878 - val_loss: 0.0654 - val_accuracy: 0.9802
Epoch 7/20
60000/60000 - 6s - loss: 0.0331 - accuracy: 0.9891 - val_loss: 0.0712 - val_accuracy: 0.9793
Epoch 8/20
60000/60000 - 6s - loss: 0.0315 - accuracy: 0.9894 - val_loss: 0.0678 - val_accuracy: 0.9803
Epoch 9/20
60000/60000 - 6s - loss: 0.0271 - accuracy: 0.9910 - val_loss: 0.0688 - val_accuracy: 0.9827
Epoch 10/20
60

In [43]:
# saving the model0.9947
save_dir = "results\\"
model_name = 'machineteam'
model_path = os.path.join(save_dir, model_name)
model.save(model_path)
print('Saved trained model at %s ' % model_path)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: results\machineteam\assets
Saved trained model at results\machineteam 


In [47]:
image_index = 7777 # You may select anything up to 60,000
print(y_train[image_index]) # The label is 8
plt.imshow(x_train[image_index], cmap='Greys')

8


In [55]:
mnist_model = load_model("results/machineteam")

print(X_test.shape)
print(Y_test.shape)
loss_and_metrics = mnist_model.evaluate(X_test, Y_test, verbose=2)

print("Test Loss", loss_and_metrics[0])
print("Test Accuracy", loss_and_metrics[1])

(10000, 28, 28)
(10000, 10)


ValueError: Error when checking input: expected dense_input to have 2 dimensions, but got array with shape (10000, 28, 28)

In [56]:
# load the model and create predictions on the test set
mnist_model = load_model("results/machineteam")
predicted_classes = mnist_model.predict_classes(X_test)

# see which we predicted correctly and which not
correct_indices = np.nonzero(predicted_classes == y_test)[0]
incorrect_indices = np.nonzero(predicted_classes != y_test)[0]
print()
print(len(correct_indices)," classified correctly")
print(len(incorrect_indices)," classified incorrectly")

# adapt figure size to accomodate 18 subplots
plt.rcParams['figure.figsize'] = (7,14)

figure_evaluation = plt.figure()

# plot 9 correct predictions
for i, correct in enumerate(correct_indices[:9]):
    plt.subplot(6,3,i+1)
    plt.imshow(X_test[correct].reshape(28,28), cmap='gray', interpolation='none')
    plt.title(
      "Predicted: {}, Truth: {}".format(predicted_classes[correct],
                                        y_test[correct]))
    plt.xticks([])
    plt.yticks([])

# plot 9 incorrect predictions
for i, incorrect in enumerate(incorrect_indices[:9]):
    plt.subplot(6,3,i+10)
    plt.imshow(X_test[incorrect].reshape(28,28), cmap='gray', interpolation='none')
    plt.title(
      "Predicted {}, Truth: {}".format(predicted_classes[incorrect], 
                                       y_test[incorrect]))
    plt.xticks([])
    plt.yticks([])

plt.figure(figsize = (20, 10))

ValueError: Error when checking input: expected dense_input to have 2 dimensions, but got array with shape (10000, 28, 28)