# NumPy Tutorial

https://www.machinelearningplus.com/python/numpy-tutorial-part1-array-python-examples/

# Intro to NumPy

Numpy is the most basic and a powerful package for working with data in python. 
NumPy is used in many other packages in python even though you may not see it explicitly running in your code. 

If you are going to work on data analysis or machine learning projects, then having a solid understanding of numpy is nearly mandatory.

Because other packages for data analysis (like pandas) is built on top of numpy and the scikit-learn package which is used to build machine learning applications works heavily with numpy as well.

It is a python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

#### Import the numpy package and print the version number

In [30]:
import numpy as np
print(np.__version__)

1.14.3


#### Make an array from a list. 

This will create a numpy array with 3 elements. 

Each numpy array contains an attribute called `shape`. Shape is a tuple which tells you how many elements you have per axis. For example (5, 6, 8) means 5 elements per axis 0, 6 elements per axis 1 and 8 elements per axis 2. Usually you will have only one or two axes.

The shape for the array in this section is `(3, )`. The reason for this funny notation is python's type system where shape must be a tuple and this is a tuple with 1 element. Writing just 3 would mean a number, not a tuple.

To verify that try `np.array([1, 2, 3]).shape` 

In [62]:
np.array([1, 2, 3])

array([1, 2, 3])

In [63]:
# Print the array and its type

a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


The key difference between an array and a list is, arrays are designed to handle vectorized operations while a python list is not.

That means, if you apply a function it is performed on every item in the array, rather than on the whole array object.

Let’s suppose you want to add the number 2 to every item in the list. The intuitive way to do it is something like this:

In [64]:
list1 = [1, 2, 3, 4]
list1 + 2    # error

TypeError: can only concatenate list (not "int") to list

That was not possible with a list. But you can do that on a ndarray.

In [65]:
a = np.array([1, 2, 3, 4]) + 2
print(a)

[3 4 5 6]


#### Make an array from a list of lists

The shape of this array is (2, 2) so this is a matrix. This creates a matrix like a 2d array.

In [66]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

You may also specify the datatype by setting the dtype argument. Some of the most commonly used numpy dtypes are: 'float', 'int', 'bool', 'str' and 'object'.

To control the memory allocations you may choose to use one of ‘float32’, ‘float64’, ‘int8’, ‘int16’ or ‘int32’.

In [67]:
list1 = [[1, 2], [3, 4]]
x = np.array(list1, dtype='float')
print(x.dtype)
print(x)

float64
[[1. 2.]
 [3. 4.]]


Convert to 'int' datatype

In [68]:
x = x.astype(int)
print(y)

[200   1   2   3   4   5   6   7   8   9  10  11]


## Inspecting the size and shape

Let’s suppose you were handed a numpy vector that you didn’t create yourself. What are the things you would want to explore in order to know about that array?

Well, I want to know:

<li>If it is a 1D or a 2D array or more. (ndim)</li>

<li>How many items are present in each dimension (shape)</li>

<li>What is its datatype (dtype)</li>

<li>What is the total number of items in it (size)</li>

<li>Samples of first few items in the array (through indexing)</li>

#### Create a 2d array with 3 rows and 4 columns

In [69]:
x = np.array([[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]])
x

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [70]:
# shape
print('Shape: ', x.shape)

# dtype
print('Datatype: ', x.dtype)

# size
print('Size: ', x.size)

# ndim
print('Num Dimensions: ', x.ndim)

Shape:  (3, 4)
Datatype:  int32
Size:  12
Num Dimensions:  2


## Indexing Arrays

#### Access elements of a 1-dimensional array.  Get the first and last element.

In python as is in many other programming languages all arrays start from 0 so the first element is at position 0.

To access the last element we can use -1 as the index. `x[-1]` is identical to `x[x.shape[0] - 1]` where `shape[0]` is the length of the array.

In [71]:
x = np.arange(4)
print(x[0])
print(x[-1])

0
3


#### Reshape an array

Remember that shape is the fundamenal property of each array and we can modify it as we desire and we often do so. To change the shape of an array we use the `reshape` method.

The code in this example creates an 1D-array of 6 elements using the `arange` functon.

In [72]:
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


We convert it to a 2D-array using the `reshape` method.

You see that the total amount of numbers did not change, only our view of them. 6 elements in a vector or 3 x 2 elements in a matrix.

It is very important that when using `reshape` to ensure that dimensions match or you will get an error. 6 = 3 x 2 is a match so this works but trying np.arange(6).reshape(4, 2) will give you an error. 

[docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)

In [73]:
x = np.arange(6).reshape(2, 3)
print(x)

[[0 1 2]
 [3 4 5]]


#### Get the last row

When dealing with arrays which are of more than a single dimension we can use partial indexing specifications go slice the array the way we want. 

For example `print(x[-1])` will print the last **row**.

To get the last column take the transpose of the 2d-array and then use [-1]. 

For exampe `print(x.T[-1])` will give you the last columns. `x.T` is the transpose of `x`

In [74]:
print(x[-1])

[3 4 5]


#### Get elements like a list

Using the notation `a:b` we can slice arrays as precisely as we want.

`a:b` means give me back all elements whose positions is in that set.

For example `y = [1, 3, 5, 7, 9]` and `y[0:2]` would give us the first two elements `[1, 3]`.

Negative indices mean from back so -3 means 3 positions starting from the last position.

Experiment with the values until you get the feel for it.

In [75]:
x = np.arange(10) 

print(x)
print(x[:3])
print(x[1:4])
print(x[-3:])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[1 2 3]
[7 8 9]


#### Get all elements in reverse order

The enhanced slicing syntax is `a:b:c` were `c` is the step. For example `0:10:2`.

If we omit `a` and `b` we always asume they are `a` = 0 and `b` = length of the list so we are only left with a step.

Thus `::2` means slicing from 0 to end with a step 2. `::3` mean slicing with a step 3.

Now what if we used negative steps. Using -1 as the step would reverse the logic and `a` becomes the end of the list and `b` becomes zero. So `::-1` will slice in reverse direction.

Finally there is also the slice form `::1` or written short `:` which means give me back all elements in order as they are present.

In [76]:
print(x[::-1])

[9 8 7 6 5 4 3 2 1 0]


#### Create a 5x5 matrix

In [77]:
x = np.arange(25).reshape(5, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Using -1 in the reshape(), it allows Python determine its size.

In [78]:
x = np.arange(25).reshape(5, -1)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### Get the first two columns and the first two rows

Until now you have learned how to slice on a 1D array but slices can be generalized to any dimensional arrays.

The trick is to create a slice for every dimensions. 

In this example we have a 2d-array so we create two slices, one for dimension 0 (rows) and one for dimension 1 (columns)

In [79]:
print(x[:2, :2])

[[0 1]
 [5 6]]


#### Get every second column of every second row

In [80]:
print(x[::2, ::2])

[[ 0  2  4]
 [10 12 14]
 [20 22 24]]


#### Reverse the rows and the whole array

Reversing an array works like how you would do with lists, but you need to do for all the axes (dimensions) if you want a complete reversal.

In [81]:
# Reverse only the row positions

x[::-1, ]

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [82]:
# Reverse the row and column positions

x[::-1, ::-1]

array([[24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

## Access parts of an array with index arrays

#### Generate six random integers between 0 and 9 inclusive

`randint` in `np.random` is a very useful function which generates uniformly distributed random integers from the range provided as its first two parameters (start and end of range respectively). It's third parameter tells the method how many numbers we need.

In [83]:
x = np.random.randint(0, 10, 6) 
print(x)

[1 3 7 9 2 4]


#### Get the first number and the last two numbers

Slices are inhetently linear and give us access to arrays in a linear fashion.

To access elements in any order we must use index arrays which are numpy arrays holding integer numbers which tell what elements to chose from the indexed array.

In [84]:
indices = [0, -2, -1]
print(x[indices])

[1 2 4]


#### Create two arrays

The array `x2` is created as `x1 * -1`. The multiplication operator here means multiply all elements of `x1` with -1 and give back that as result.

In [85]:
arrayLength = 5
x1 = np.arange(arrayLength)
x2 = np.arange(arrayLength) * -1

print(x1)
print(x2)

[0 1 2 3 4]
[ 0 -1 -2 -3 -4]


#### Create a random shuffled range of numbers

This and the following example shows how to shuffle an array in numpy.

Shuffling means reoreding the items in an array and we can do that using random permutations of the array positions.

In [86]:
indices = np.random.permutation(arrayLength)
print(indices)

[1 0 3 2 4]


#### Use indices to re-order arrays

In [87]:
print(x1[indices])
print(x2[indices])

[1 0 3 2 4]
[-1  0 -3 -2 -4]


#### Use boolean values to index arrays

Once we have created our boolean array we can use it to index other arrays.

The rule is very simple. If at position i of index we have True include `x[i]` in the output.

In [88]:
x = np.arange(5)
print(x)
print(x > 2)

[0 1 2 3 4]
[False False False  True  True]


#### Use boolean values to index arrays

Once we have created our boolean array we can use it to index other arrays.

The rule is very simple. If at position i of index we have True include `x[i]` in the output.

In [89]:
print(x[x > 2])
print(x[np.array([False,False,False,True,True])])

[3 4]
[3 4]


## Create a new array from an existing array

If you just assign a portion of an array to another array, the new array you just created actually refers to the parent array in memory. 

That means, if you make any changes to the new array, it will reflect in the parent array as well.

So to avoid disturbing the parent array, you need to make a copy of it using copy(). All numpy arrays come with the copy() method.

In [90]:
# Assign portion of x to y. Doesn't really create a new array.
x = np.array(np.arange(12)).reshape(3, 4)
print(x)
y = x[:2,:2]  
y[:1, :1] = 100  # 100 will reflect in x
x

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [91]:
# Copy portion of x to y
y = x[:2, :2].copy()
y[:1, :1] = 200  # 200 will not reflect in arr2
x

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

## Reshaping and Flattening Multidimensional arrays

Reshaping is changing the arrangement of items so that shape of the array changes while maintaining the same number of dimensions.

Flattening, however, will convert a multi-dimensional array to a flat 1d array. And not any other shape.

First, let’s reshape the x array from 3×4 to 4×3 shape.

In [92]:
print(x)
x.reshape(4, 3)

[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11]])

#### flatten() and ravel()

There are 2 popular ways to implement flattening. That is using the flatten() method and the other using the ravel() method.

The difference between ravel and flatten is, the new array created using ravel is actually a reference to the parent array. So, any changes to the new array will affect the parent as well. But is memory efficient since it does not create a copy.

In [93]:
# Flatten it to a 1d array
x.flatten()

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [94]:
# Changing the flattened array does not change parent
y = x.flatten()  
y[0] = 200  # changing b1 does not affect x
x

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [95]:
# Changing the raveled array changes the parent also.
y = x.ravel()  
y[0] = 200  # changing y changes x also
x

array([[200,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

## Make an array using a function

The arrays made in previous sections were based on us supplying each value.

Very often we need large arrays and it is not possible to use our current approach and thus we need to use array creating functions. The most important functions are `zeros` and `ones`. They both take a parameter called shape which determines the shape of the output array.
* `zeros` makes an array which is all 0 [docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html)
* `ones`  makes an array which is all 1 [docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones)

In [96]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [97]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#### Make an array by starting at 0, incrementing by 2 and ending before 10

`arange` is the exact same thing as regular python `range` except giving back a numpy array.

This functions requires only a single argument which is the end point. The start point is assumed to be 0 and step is assumed to be 1.

In this variety when in takes three parameters, the first one is the start, second one is the end and the third one is the step.

[docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)

In [98]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

#### Make an array that has 6 to 1 decreasing order, 2x3 matrix

In [99]:
x = np.arange(6, 0, -1).reshape(2, 3)
print(x)

[[6 5 4]
 [3 2 1]]


#### Make an array of four evenly spaced numbers including both endpoints

In [100]:
np.linspace(0, 1, 4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

#### Make an array of random numbers (using a normal distribution)

The random submodule of numpy contains a variety of functions for generating random numbers following a specified probability distributions or sampling from a finite set of choices. To learn more about it visit the [documentation](https://docs.scipy.org/doc/numpy/reference/routines.random.html). 

In [101]:
mean = 10
stdev = 3
number_values = 20
np.random.normal(mean, stdev, number_values)

array([11.7406582 , 14.69979836, 10.30173196,  7.79864842, 11.71494741,
        5.10187824,  4.2769548 , 11.8333877 ,  7.15570107,  8.39305134,
        9.16098869,  8.51325015,  6.76258925, 12.16554804, 13.23488203,
        7.74870507, 12.50510658, 13.17201229,  8.14344557, 12.83159958])

## Array Math

#### Compute mean, min, max on the ndarray

In [102]:
x = np.array(np.arange(12)).reshape(3, -1)
print(x)
# mean, max and min
print("Mean value is: ", x.mean())
print("Max value is: ", x.max())
print("Min value is: ", x.min())


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Mean value is:  5.5
Max value is:  11
Min value is:  0


#### Compute min in row wise and column wise

In [103]:
# Row wise and column wise min
print("Column wise minimum: ", np.amin(x, axis=0))
print("Row wise minimum: ", np.amin(x, axis=1))

Column wise minimum:  [0 1 2 3]
Row wise minimum:  [0 4 8]


### Exercises

Create an array from 0 to 26 assign it to a variable x

Reverse the order of the array and print it out

Convert the 1-dimensional array you created into a 3 dimensional array

Find the index (location) for value 12

Create a random shuffled list of values from 0-19 and assign it to variable y

Create an array of boolean values for values in y that are greater than 10

Create a random sample of 20 data points from a normal distribution with mean of 10 and standard deviation 5

# NumPy Tutorial 2: Advanced Topics for Machine Learning

This is part 2 of a NumPy tutorial. In this part, I go into the details of the advanced features of NumPy that are essential for machine learning data analysis and manipulations.

## Get index locations that satisfy a given condition

- np.where()
- np.take()
- np.argmax()
- np.argmin()

Sometimes we want to know the index positions of the items (that satisfy a condition) and do whatever you want with it.

`np.where` locates the indices in the array where a given condition holds true.

In [8]:
# Create an array
import numpy as np
x = np.array([1, 8, 3, 7, 9, 2, 0, 8, 5, 2])
print("Array: ", x)

Array:  [1 8 3 7 9 2 0 8 5 2]


#### Find all indices where the value is greater than 5

In [9]:
# Positions where value > 5
index_gt5 = np.where(x > 5)
print("Indices where value > 5: ", index_gt5)

Indices where value > 5:  (array([1, 3, 4, 7], dtype=int64),)


#### Extract the values using the array’s `np.take` method once you have the indices.

In [10]:
# Take items at given index
x.take(index_gt5)

array([[8, 7, 9, 8]])

#### Find the location of the maximum and minimum values as well.

In [11]:
# Location of the max
print('Index of max value: ', np.argmax(x))  

# Location of the min
print('Index of min value: ', np.argmin(x)) 

Index of max value:  4
Index of min value:  6


## Save and load NumPy objects

At some point, we will want to save large transformed numpy arrays to disk and load it back to console directly without having the re-run the data transformations code.

Numpy provides the `.npy` and the `.npz` file types for this purpose.

If you want to store a single ndarray object, store it as a `.npy` file using `np.save`. This can be loaded back using the `np.load`.

If you want to store more than 1 ndarray object in a single file, then save it as a `.npz` file using `np.savez`.

#### Save array object(s)

In [ ]:
# Save single numpy array object as .npy file
np.save('myarray.npy', x)  

# Save multile numy arrays as a .npz file
np.savez('myarray.npz', arr2d_f, arr2d_b)

#### Load back the .npy file.

In [ ]:
# Load a .npy file
a = np.load('myarray.npy')
print(a)

Load back the .npz file.
# Load a .npz file
b = np.load('myarray.npz')
print(b)

## Concatenate two arrays columnwise and row wise

There are 3 different ways of concatenating two or more numpy arrays.

- Method 1: np.concatenate by changing the axis parameter to 0 and 1
- Method 2: np.vstack and np.hstack
- Method 3: np.r_ and np.c_

All three methods provide the same output.

One key difference to notice is unlike the other 2 methods, both np.r_ and np.c_ use square brackets to stack arrays. But first, let me create the arrays to be concatenated.

In [13]:
a = np.zeros([3, 3])
b = np.ones([3, 3])
print(a)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# Vertical Stack Equivalents (Row wise)
np.concatenate([a, b], axis=0)  
np.vstack([a,b])  
np.r_[a,b] 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

That was what we wanted. Let’s do it horizontally (columns wise) as well.

In [ ]:
# Horizontal Stack Equivalents (Coliumn wise)
np.concatenate([a, b], axis=1) 
np.hstack([a,b])  
np.c_[a,b]

## sort an array based on one or more columns

Let’s try and sort a 2d array based on the first column.

In [15]:
x = np.random.randint(1,6, size=[6, 4])
x

array([[1, 2, 2, 2],
       [4, 1, 1, 3],
       [1, 3, 4, 2],
       [2, 1, 3, 3],
       [2, 2, 1, 5],
       [1, 4, 4, 3]])

We have a random array of 6 rows and 4 columns.

If you use the `np.sort` function with `axis=0`, all the columns will be sorted in ascending order independent of eachother, effectively compromising the integrity of the row items. In simple terms, the values in each row gets corrupted with values from other rows.

In [16]:
# Sort each columns of x
np.sort(x, axis=0)

array([[1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 2, 2, 3],
       [2, 2, 3, 3],
       [2, 3, 4, 3],
       [4, 4, 4, 5]])

##  vectorize – Make a scalar function work on vectors

With the help of vectorize() you can make a function that is meant to work on individual numbers, to work on arrays.

Let’s see a simplified example.

The function foo (see code below) accepts a number and squares it if it is ‘odd’ else it divides it by 2. When you apply this function on a scalar (individual numbers) it works perfectly, but fails when applied on an array. 

With numpy’s vectorize(), you can magically make it work on arrays as well.

In [17]:
# Define a scalar function
def foo(x):
    if x % 2 == 1:
        return x**2
    else:
        return x/2

# On a scalar
print('x = 10 returns ', foo(10))
print('x = 11 returns ', foo(11))

# On a vector, doesn't work
# print('x = [10, 11, 12] returns ', foo([10, 11, 12]))  # Error 

x = 10 returns  5.0
x = 11 returns  121


Let’s vectorize foo() so it will work on arrays.

In [18]:
# Vectorize foo(). Make it work on vectors.
foo_v = np.vectorize(foo, otypes=[float])

print('x = [10, 11, 12] returns ', foo_v([10, 11, 12]))
print('x = [[10, 11, 12], [1, 2, 3]] returns ', foo_v([[10, 11, 12], [1, 2, 3]]))

x = [10, 11, 12] returns  [  5. 121.   6.]
x = [[10, 11, 12], [1, 2, 3]] returns  [[  5. 121.   6.]
 [  1.   1.   9.]]


This can be very handy whenever you want to make a scalar function work on arrays.

`vectorize` also accepts an optional otypes parameter where you provide what the datatype of the output should be. It makes the vectorized function run faster.

## add a new axis to a array

Sometimes you might want to convert a 1D array into a 2D array (like a spreadsheet) without adding any additional data.

You might need this in order a 1D array as a single column in a csv file, or you might want to concatenate it with another array of similar shape. Whatever the reason be, you can do this by inserting a new axis using the `np.newaxis`.

Actually, using this you can raise an array of a lower dimension to a higher dimension.

In [19]:
# Create a 1D array
x = np.arange(5)
print('Original array: ', x)

Original array:  [0 1 2 3 4]


#### Add a new column axis

In [20]:
# Introduce a new column axis
x_col = x[:, np.newaxis]
print('x_col shape: ', x_col.shape)
print(x_col)

x_col shape:  (5, 1)
[[0]
 [1]
 [2]
 [3]
 [4]]


#### Add a new row axis

In [21]:
# Introduce a new row axis
x_row = x[np.newaxis, :]
print('x_row shape: ', x_row.shape)
print(x_row)

x_row shape:  (1, 5)
[[0 1 2 3 4]]


## Clip

Use `np.clip` to cap the numbers within a given cutoff range. All number lesser than the lower limit will be replaced by the lower limit. Same applies to the upper limit also.

In [25]:
x = np.random.randint(0,10, size=[6, 4])
x

array([[4, 2, 6, 8],
       [8, 4, 8, 4],
       [3, 8, 3, 5],
       [3, 6, 8, 6],
       [6, 0, 6, 5],
       [2, 2, 1, 3]])

In [27]:
# Cap all elements of x to lie between 3 and 8
np.clip(x, 5, 6)

array([[5, 5, 6, 6],
       [6, 5, 6, 5],
       [5, 6, 5, 5],
       [5, 6, 6, 6],
       [6, 5, 6, 5],
       [5, 5, 5, 5]])

## Histogram and Bincount

Both histogram() and bincount() gives the frequency of occurences. But with certain differences.

While histogram() gives the frequency counts of the bins, bincount() gives the frequency count of all the elements in the range of the array between the min and max values. Including the values that did not occur.

In [28]:
# Bincount example
x = np.array([1,1,2,2,2,4,4,5,6,6,6]) # doesn't need to be sorted
np.bincount(x) # 0 occurs 0 times, 1 occurs 2 times, 2 occurs thrice, 3 occurs 0 times, ...

array([0, 2, 3, 0, 2, 1, 3], dtype=int64)

In [29]:
# Histogram example
counts, bins = np.histogram(x, [0, 2, 4, 6, 8])
print('Counts: ', counts)
print('Bins: ', bins)

Counts:  [2 3 3 3]
Bins:  [0 2 4 6 8]


# Further Study and Assignments:

## 1. Group Assignment:

1. Watch Gordon's lecture `Machine Learning Recipes 6 ~ 7`. In one jupyter notebook, do coding for TFLearn or in Machine Learning Recipes 6 ~ 7 Video. Post your work at Piazza by 24 hours before the next class. Have a reasonably good document of the program as you have seen in my lecture note. 

    - Work with Tensorflow if possible 
    - Get familiar with MNIST Classification.
    - Find the accuracy of each digit


## 2. Reading & Programming Assignment for all

1.	"Make your own neural network" by  Tariq Rashid - This book is available in e-book form from amazon.com.  It costs you a few dollars. You are expected to have a copy of the required textbook. 

    - Read Part 2 - MNIST ANN Implementation 
    - Implement ANN for MNIST as implemented in the book
    - Find the number of samples of each digit in MNIST test and train dataset .
    - Find the accuracy of each digit
  
2. We take a turn to present some of homework assignments. Group 4 will present the material from this reading assignment for 30~40 minutes in the next class.   In the following class or the last class, Group 5 will work on the rest of the book such as the evaluation, feed backward and recognizing your own handwritten digit problem.   
