--------------
# NumPy Exercises
-------------

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays.

It is the fundamental package for scientific computing with Python. It contains various features including these important ones:

- A powerful N-dimensional array object
- Sophisticated (broadcasting) functions
- Tools for integrating C/C++ and Fortran code
- Useful linear algebra, Fourier transform, and random number capabilities

#### 1. Arrays in NumPy: NumPy’s main object is the homogeneous multidimensional array.

- It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
- In NumPy dimensions are called axes. The number of axes is rank.
- NumPy’s array class is called ndarray. It is also known by the alias array.

#### 2. Array creation: There are various ways to create arrays in NumPy.

- For example, you can create an array from a regular Python `list` or `tuple` using the `array` function. The type of the resulting array is deduced from the type of the elements in the sequences.

- Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with __initial placeholder content__. These minimize the necessity of growing arrays, an expensive operation.
__For example:__ np.zeros, np.ones, np.full, np.empty, etc.

- To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.

- __arange:__ returns evenly spaced values within a given interval. `step` size is specified.
- __linspace:__ returns evenly spaced values within a given interval. __num__ no. of elements are returned.

- __Reshaping array:__ We can use `reshape` method to reshape an array. Consider an array with shape (a1, a2, a3, …, aN). We can reshape and convert it into another array with shape (b1, b2, b3, …, bM). The only required condition is:
a1 x a2 x a3 … x aN = b1 x b2 x b3 … x bM . (i.e original size of array remains unchanged.)

- __Flatten array:__ We can use `flatten` method to get a copy of array collapsed into _one dimension_. It accepts order argument. Default value is ‘C’ (for row-major order). Use ‘F’ for column major order.

In [1]:
import numpy as np
print(np.__version__)

1.14.2


__JoyQ1__: Create a 1D array of numbers from 0 to 9

Desired output:

```
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])```


In [2]:
x = np.arange(10)

__JoyQ2__: Create a 3×3 numpy array of all True’s

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

__JoyQ3__: Create a 3×3 numpy array of all True’s

Extract all odd numbers from x

Input:
```
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Desired Output:
```
#> array([1, 3, 5, 7, 9])
```

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution


array([1, 3, 5, 7, 9])

__JoyQ4__: Replace all odd numbers in x with -1

Input:
```
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Desired Output:
```
#> array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
```

In [6]:

print(x)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

__JoyQ5__: Replace all odd numbers in x with -1 without changing x
    
Input:
```
x =  np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Desired Output:
out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
x
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [10]:
x = np.arange(10)
out = 
print(x)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


__JoyQ6__:Convert a 1D array to a 2D array with 2 rows
    
Input:
```
x =  np.arange(10)
```

Desired Output:
out
```
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])
```

In [13]:
x = np.arange(10)

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

__JoyQ7__: Stack arrays a and b vertically
    
Input:
```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

Desired Output:
out
```
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])
```

In [16]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Answers


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

__JoyQ8__: Stack the arrays a and b horizontally.
    
Input:
```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

Desired Output:
out
```
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Answers


__JoyQ 9__:  Get the positions where elements of a and b match
    
Input:
```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,1,2,7,4,9,4,9,8])
```

Desired Output:
```
#> (array([1, 3, 5, 7]),)
```

In [ ]:
np.where(a == b)

__JoyQ10:__ Extract all numbers between a given range from an array

Get all items between 5 and 10 from a.
Input:
```
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

Desired Output:
```
#> (array([6, 9, 10]),)
```

In [3]:
import numpy as np

a = np.array([2, 6, 1, 9, 10, 3, 27])


array([ 6,  9, 10])

__JoyQuiz 11:__ Convert the function `maxy` that works on two scalars, to work on two arrays. Replace None in the following code.

Input:
```
def maxy(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
```
Desired Output:
```
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
```

In [ ]:
def maxy(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = None  ########### Your code replaces None ###########

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

__JoyQuiz 12:__ Swap columns 1 and 2 in the array arr.

In [4]:
x = np.arange(9).reshape(3,3)
print(x)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
# your code here

print(x)

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

__JoyQuiz 13:__ Swap rows 1 and 2 in the array arr:


In [11]:
x = np.arange(9).reshape(3,3)
print(x)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
# your code here

print(x)

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

__JoyQuiz 14:__ Find the most frequent value in an array?

In [3]:
x = np.random.randint(0,10,50)



__JoyQuiz 15:__ Count the number of different elements in two arrays.


In [2]:
x = np.random.randint(0,3,20)
y = np.random.randint(0,3,20)
print(x)
print(y)



[2 2 2 2 0 2 0 1 2 0 0 0 0 1 0 2 1 1 0 0]
[2 1 1 0 2 0 1 0 2 1 1 0 0 0 2 0 1 2 0 0]
