--------------
# NumPy Exercises
-------------

Machine Learning Plus: https://www.machinelearningplus.com/python/101-numpy-exercises-python/

__JoyQ1__: Create a 1D array of numbers from 0 to 9

Desired output:

```
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])```


In [2]:
import numpy as np
x = np.arange(10)

__JoyQ2__: Create a 3×3 numpy array of all True’s

In [3]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

__JoyQ3__: Create a 3×3 numpy array of all True’s

Extract all odd numbers from x

Input:
```
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Desired Output:
```
#> array([1, 3, 5, 7, 9])
```

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

__JoyQ4__: Replace all odd numbers in x with -1

Input:
```
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Desired Output:
```
#> array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
```

In [6]:
x[x % 2 == 1] = -1
x

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
__JoyQ5__: Replace all odd numbers in x with -1 without changing x
    
Input:
```
x =  np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Desired Output:
out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
x
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [10]:
x = np.arange(10)
out = np.where(arr % 2 == 1, -1, x)
print(x)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


__JoyQ6__:Convert a 1D array to a 2D array with 2 rows
    
Input:
```
x =  np.arange(10)
```

Desired Output:
out
```
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])
```

In [13]:
x = np.arange(10)
x.reshape(2, -1)  # Setting to -1 automatically decides the number of cols
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

__JoyQ7__: Stack arrays a and b vertically
    
Input:
```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

Desired Output:
out
```
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])
```

In [16]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Answers
# Method 1:
np.concatenate([a, b], axis=0)

# Method 2:
np.vstack([a, b])

# Method 3:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
__JoyQ8__: Stack the arrays a and b horizontally.
    
Input:
```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

Desired Output:
out
```
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Answers
# Method 1:
np.concatenate([a, b], axis=1)

# Method 2:
np.hstack([a, b])

# Method 3:
np.c_[a, b]
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

__JoyQ 9__:  Get the positions where elements of a and b match
    
Input:
```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,1,2,7,4,9,4,9,8])
```

Desired Output:
```
#> (array([1, 3, 5, 7]),)
```

In [ ]:
np.where(a == b)

__JoyQ10:__ Extract all numbers between a given range from an array

Get all items between 5 and 10 from a.
Input:
```
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

Desired Output:
```
#> (array([6, 9, 10]),)
```

In [3]:
import numpy as np

a = np.array([2, 6, 1, 9, 10, 3, 27])
# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

# Method 3: 
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

__JoyQ 11:__ Convert the function `maxx` that works on two scalars, to work on two arrays.

Input:
```
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
```
Desired Output:
```
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
```

In [ ]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

__JoyQuiz 12:__ Swap columns 1 and 2 in the array arr.

In [4]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
x[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

__JoyQui 13:__ Swap rows 1 and 2 in the array arr:


In [11]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
x[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])